plugins {
    id 'com.android.application'
}

android {
    namespace 'com.github.rove24.wellbeing'
    compileSdk 34

    defaultConfig {
        applicationId "com.github.rove24.wellbeing"
        minSdk 26
        targetSdk 34
        versionCode 25
        versionName "2.5"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }
}

dependencies {
    compileOnly 'io.github.libxposed:api:102.0.0'
    compileOnly 'de.robv.android.xposed:api:82'
    compileOnly 'androidx.annotation:annotation:1.6.0'
}